# Generated by Django 4.1.1 on 2022-10-08 08:10

from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_name', models.CharField(max_length=30, verbose_name='name')),
                ('carousel_about', models.TextField(verbose_name='about')),
                ('carousel_image', models.ImageField(upload_to=main_page.models.MyCarousel.get_file_name, verbose_name='photo')),
                ('carousel_access', models.BooleanField(default=True, verbose_name='acces')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='Event price')),
                ('description', models.TextField(max_length=1000)),
                ('subtitle1', models.TextField(blank=True, verbose_name='sub1')),
                ('subtitle2', models.TextField(blank=True, verbose_name='sub2')),
                ('subtitle3', models.TextField(blank=True, verbose_name='sub3')),
                ('aftertitle', models.TextField(blank=True, verbose_name='After text')),
                ('photo', models.ImageField(upload_to=main_page.models.Events.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Gallery.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whuus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whuus_order', models.SmallIntegerField(unique=True, verbose_name='Position')),
                ('whuus_title', models.CharField(max_length=20, verbose_name='Title')),
                ('whuus_about', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Why us',
                'verbose_name_plural': 'Why us',
                'ordering': ('whuus_order',),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_special', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField()),
                ('ingredients', models.TextField(max_length=1000)),
                ('desc', models.TextField(blank=True, max_length=1000)),
                ('photo', models.ImageField(upload_to=main_page.models.Dish.get_file_name)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.category')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'ordering': ('position',),
            },
        ),
    ]
