# Generated by Django 4.1.1 on 2022-10-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel',
            new_name='MyCarousel',
        ),
        migrations.AlterModelOptions(
            name='mycarousel',
            options={'verbose_name': 'MyCarousel', 'verbose_name_plural': 'MyCarousel'},
        ),
    ]
