# Generated by Django 4.1.1 on 2022-10-10 12:08

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_rename_carousel_mycarousel_alter_mycarousel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefs_order', models.SmallIntegerField(unique=True)),
                ('chefs_name', models.CharField(max_length=30, verbose_name='name')),
                ('chefs_pro', models.CharField(max_length=30, verbose_name='profession')),
                ('chefs_twitter', models.CharField(blank=True, max_length=50, verbose_name='teitter')),
                ('chefs_facebook', models.CharField(blank=True, max_length=50, verbose_name='facebook')),
                ('chefs_instagram', models.CharField(blank=True, max_length=50, verbose_name='instagram')),
                ('chefs_linkedin', models.CharField(blank=True, max_length=50, verbose_name='linkedin')),
                ('chefs_photo', models.ImageField(upload_to=main_page.models.Chefs.get_file_name, verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Chefs',
                'verbose_name_plural': 'Chefsі',
                'ordering': ('chefs_order',),
            },
        ),
    ]
