# Generated by Django 4.1.1 on 2022-10-10 16:07

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_chefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotions_order', models.SmallIntegerField(unique=True)),
                ('emotions_name', models.CharField(max_length=30, verbose_name='name')),
                ('emotions_pro', models.CharField(max_length=30, verbose_name='profession')),
                ('emotions_photo', models.ImageField(upload_to=main_page.models.Emotions.get_file_name, verbose_name='Photo')),
                ('emotions_rating', models.SmallIntegerField(help_text='1-5')),
                ('emotions_message', models.TextField(max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Emotions',
                'verbose_name_plural': 'Emotions',
                'ordering': ('emotions_order',),
            },
        ),
        migrations.AlterModelOptions(
            name='chefs',
            options={'ordering': ('chefs_order',), 'verbose_name': 'Chefs', 'verbose_name_plural': 'Chefs'},
        ),
    ]
