# Generated by Django 4.1.1 on 2022-10-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservations',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreservations',
            name='num_of_people',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreservations',
            name='order_date',
            field=models.TextField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreservations',
            name='order_time',
            field=models.TextField(default='exit', max_length=6),
            preserve_default=False,
        ),
    ]
