# Generated by Django 4.1.1 on 2022-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_userreservations_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreservations',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='userreservations',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
